config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users

  # Defines the root path route ("/")
  root to: "pages#home"

  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/share_group.rb
class ShareGroup < ApplicationRecord
  validates :name, presence: true

  has_many :todos, dependent: :destroy
  has_many :users
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :summary, presence: true

  belongs_to :share_group

  scope :ordered, -> { order(created_at: :desc) }

  # after_create_commit -> { broadcast_prepend_later_to "todos" }
  # after_update_commit -> { broadcast_replace_later_to "todos" }
  # after_destroy_commit -> { broadcast_remove_to "todos" }
  broadcasts_to ->(todo) { [todo.share_group, "todos"] }, inserts_by: :prepend
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :registerable, :recoverable, :rememberable,
  devise :database_authenticatable, :validatable

  belongs_to :share_group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?
  helper_method :current_share_group

  private

  def current_share_group
    @current_share_group ||= current_user.share_group if user_signed_in?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %w[show edit update destroy]

  def index
    @todos = current_share_group.todos.ordered
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = current_share_group.todos.build(todo_params)

    if @todo.save
      message = "New todo added!"

      respond_to do |format|
        format.turbo_stream { flash.now[:notice] = message }
        format.html { redirect_to todos_path, notice: message }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      message = "Todo successfully updated."

      respond_to do |format|
        format.html { redirect_to todos_path, notice: message }
        format.turbo_stream { flash.now[:notice] = message }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @todo.destroy

    message = "Todo successfully deleted."
    respond_to do |format|
      format.html { redirect_to todos_path, notice: message }
      format.turbo_stream { flash.now[:notice] = message }
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:summary)
  end

  def set_todo
    @todo = current_share_group.todos.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend "flash", partial: "layouts/flash"
  end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message"
    data-controller="removals"
    data-action="animationend->removals#remove"
  >
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="navbar">
  <% if user_signed_in? %>
    <div class="navbar__brand">
      <%= current_share_group.name %>
    </div>
    <div class="navbar__name">
      <%= current_user.email %>
    </div>
    <%= button_to "Sign out",
                  destroy_user_session_path,
                  method: :delete,
                  class: "btn btn--dark" %>
  <% else %>
    <%= link_to "Sign in",
                new_user_session_path,
                class: "btn btn--dark navbar__right" %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Checklister</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div id="flash" class="flash">
      <%= render "layouts/flash" %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<main class="container">
  <h1>Shared Todo List</h1>
  <p>Share your Todo lists with your family!</p>

  <% if user_signed_in? %>
    <%= link_to "View todos", todos_path, class: "btn btn--dark" %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path, class: "btn btn--dark" %>
  <% end %>
</main>

app/views/todos/_empty_state.html.erb
<div class="empty-state empty-state--only-child">
  <p class="empty-state__text">
    You don't have any Todos yet!
  </p>

  <%= link_to "Add todo",
              new_todo_path,
              class: "btn btn--primary",
              data: { turbo_frame: dom_id(Todo.new) } %>
</div>

app/views/todos/_form.html.erb
<%= simple_form_for todo, html: { class: "todo form" } do |f| %>
  <% if todo.errors.any? %>
    <div class="error-message">
      <%= todo.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.input :summary, input_html: { autofocus: true } %>

  <div class="form__actions">
    <%= link_to "Cancel", todos_path, class: "btn btn--light" %>
    <%= f.submit class: "btn btn--secondary" %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<%= turbo_frame_tag todo do %>
  <div class="todo">
    <%= link_to todo.summary, todo_path(todo), data: { turbo_frame: "_top" } %>
    <div class="todo__actions">
      <%= button_to "Done",
                    todo_path(todo),
                    method: :delete,
                    class: "btn btn--light" %>
      <%= link_to "Edit",
                  edit_todo_path(todo),
                  class: "btn btn--light" %>
    </div>
  </div>
<% end %>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.prepend "todos", @todo %>
<%= turbo_stream.update Todo.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/todos/destroy.turbo_stream.erb
<%= turbo_stream.remove @todo %>

app/views/todos/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to todo"), todo_path(@todo) %>

  <div class="header">
    <h1>Edit Todo</h1>
  </div>

  <%= turbo_frame_tag @todo do %>
    <%= render "form", todo: @todo %>
  <% end %>
</main>

app/views/todos/index.html.erb
<%= turbo_stream_from current_share_group, "todos" %>

<main class="container">
  <div class="header">
    <h1>Checklist</h1>
    <%= link_to "New Todo",
                new_todo_path,
                data: { turbo_frame: dom_id(Todo.new) },
                class: "btn btn--primary" %>
  </div>

  <%= turbo_frame_tag Todo.new %>

  <%= turbo_frame_tag "todos" do %>
    <%= render "todos/empty_state" %>
    <%= render @todos %>
  <% end %>
</main>

app/views/todos/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to todos"), todos_path %>

  <div class="header">
    <h1>New Todo</h1>
  </div>

  <%= turbo_frame_tag @todo do %>
    <%= render "form", todo: @todo %>
  <% end %>
</main>

app/views/todos/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to todos"), todos_path %>
  <div class="header">
    <h1>
      <%= @todo.summary %>
    </h1>
  </div>
</main>

app/views/todos/update.turbo_stream.erb
<%= turbo_stream.replace @todo %>
<%= render_turbo_stream_flash_messages %>